weather page group 3
rogersm-uwosh/Lab6_Starter_Code pull request #4
Opened 2024-10-16 22:13 UTC by skogmanpe40

Group 3 has completed the weather screen and has synced before creating the pull request.

2024-10-19 22:12 UTC, skogmanpe40 commented
Merge conflict has been resolved

2024-10-20 16:54 UTC, rogersm-uwosh commented
Once you've addressed my code review comments, I can merge this.

2024-10-20 18:13 UTC, rogersm-uwosh commented
Because I've added some other teams since I wrote this, you'll need to pull main, resolve the conflicts, and push the PR before I'll be able to examine it

2024-10-22 00:26 UTC, rogersm-uwosh requested changes

2024-10-22 02:49 UTC, merged